import mongoose from "mongoose";

const paymentSchema = new mongoose.Schema({
    mihpayid: { type: String, required: true },
    mode: { type: String, required: true },
    status: { type: String, required: true },
    key: { type: String, required: true },
    txnid: { type: String, required: true },
    amount: { type: Number, required: true },
    addedon: { type: Date, required: true },
    productinfo: { type: String, required: true },
    firstname: { type: String, required: true },
    lastname: { type: String },
    address1: { type: String },
    address2: { type: String },
    city: { type: String },
    state: { type: String },
    country: { type: String },
    zipcode: { type: String },
    email: { type: String, required: true },
    phone: { type: String, required: true },
    udf1: { type: String },
    udf2: { type: String },
    udf3: { type: String },
    udf4: { type: String },
    udf5: { type: String },
    card_token: { type: String },
    card_no: { type: String },
    field0: { type: String },
    field1: { type: String },
    field2: { type: String },
    field3: { type: String },
    field4: { type: String },
    field5: { type: String },
    field6: { type: String },
    field7: { type: String },
    field8: { type: String },
    field9: { type: String },
    payment_source: { type: String },
    PG_TYPE: { type: String },
    error: { type: String },
    error_Message: { type: String },
    net_amount_debit: { type: Number },
    discount: { type: Number },
    offer_key: { type: String },
    offer_availed: { type: String },
    unmappedstatus: { type: String },
    hash: { type: String, required: true },
    bank_ref_no: { type: String },
    bank_ref_num: { type: String },
    bankcode: { type: String },
    surl: { type: String },
    curl: { type: String },
    furl: { type: String },
    plan: { type: mongoose.Schema.Types.ObjectId, ref: 'Plan', default: null },
}, { timestamps: true });

const Payment = mongoose.model('Payment', paymentSchema);

export default Payment;

